### ISSUE TITLE
Add citation

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#116]
we should add a citation for the readalongs paper

**Comment by joanise** [comment]
Excellent idea. Let's add a `CITATION.cff` file (see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) and maybe also put the generated BibTeX entry in the `README.md`.

Samuel just added a `CITATION.cff` to https://github.com/nrc-cnrc/PortageTextProcessing
