### ISSUE TITLE
Define our `.ras` file format with a DTD

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio#127]
Studio should output and read `.ras` files rather than just `.xml`.
The file format needs an actual DTD defining it.

**Comment by dhdaines** [comment]
Adding a reference to #142 here

**Comment by dhdaines** [comment]
And a note that using `.ras` as a file extension may not be a great idea since it is meant to be served by a web server, which will not know that it is actually just XML.

**Comment by joanise** [comment]
Fixed with #142
