### ISSUE TITLE
Allow for different Unicode normalization standards

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#14]
Currently, ReadAlong-Studio requires NFD. This creates problems with the `g2p` module because mappings in that module can use NFC, NFD, NKFC or NKFD. ReadAlong-Studio should just look at the mapping of any given language it's working with and use its declared standard.

**Comment by dhdaines** [comment]
Fun :) Is there a canonical table of the standards or should we just
declare them in the mappings?

Le mar. 22 oct. 2019, à 15 h 32, Aidan Pine <notifications@github.com> a
écrit :

**Comment by roedoejet** [comment]
Unicode is *always* fun :) hah

The `g2p` module let's you declare the standard using the key word arg `norm_form` and then gives the value to `unicodedata.normalize(norm_form, u'\u0061\u0301')`. My feeling is this is probably best, just because there could be good reasons for various mappings to use NFD or NFC.

**Comment by joanise** [comment]
Fixed with #61, specifically by no longer supporting g2p'ing sub-word units (commit 4c3917eb9)
See also #37
