### ISSUE TITLE
Web-api: set the CORS origin from a .env or parameter

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio#172]
Currently, we hard code the mothertongues URL for the allowed origin.

We need to parameterize that properly for others to deploy easily.

**Comment by dhdaines** [comment]
Actually no longer true!  You can set it with the ORIGIN environment variable: https://github.com/ReadAlongs/Studio/blob/main/readalongs/web_api.py#L15

**Comment by joanise** [comment]
Nice! I failed to notice that, but good idea.
