### ISSUE TITLE
Word Tokenizer not picking the right mapping

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#18]
The `TokenizerLibrary` class in `readalongs/text/tokenize_xml.py` overwrites tokenizers with the same input language. So, for example if there is a mapping from `git` to `git-ipa` and then a mapping from `git` to `git-apa`, the `git->git-ipa` one is overwritten by the `git-apa` one. I put a bandaid on this here: a3c414d94121293278020bee543a5d6785f09605 but this won't work if we want to tokenize/align through anything other than an ipa mapping. It also requires `out_lang` to end in `-ipa`. This should be more robust.

**Comment by joanise** [comment]
@roedoejet I'm pretty sure https://github.com/roedoejet/g2p/pull/82 fixed this issue, but it would be worth testing again to confirm it.

**Comment by joanise** [comment]
Tested, this is indeed fixed.
