### ISSUE TITLE
Strange IndexError caused by [SMACK]

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#183]
I can't provide steps to re-create this because the data is private, but while aligning a specific audio file, an IndexError is thrown when trying to get the word element:

```
File "/Users/pinea/.pyenv/versions/3.9.14/lib/python3.9/site-packages/readalongs/align.py", line 1006, in get_word_texts_and_sentences
    word_el = get_word_element(tokenized_xml, word["id"])
  File "/Users/pinea/.pyenv/versions/3.9.14/lib/python3.9/site-packages/readalongs/align.py", line 972, in get_word_element
    return xml.xpath(f'//w[@id="{el_id}"]')[0]
IndexError: list index out of range
```

A breakpoint showed that the word in question was `{'id': '[SMACK]', 'start': 74.19, 'end': 75.66}` - removing it fixes the issue, but I presume this is something coming from SoundSwallower. @dhdaines - how should we be handling this?

**Comment by dhdaines** [comment]
Ah, we *should* be filtering those noise words out, but for whatever reason we currently aren't.  No need to see the private data to fix this, I can make a PR tonight.

**Comment by roedoejet** [comment]
Fixed by https://github.com/ReadAlongs/Studio/pull/184
