### ISSUE TITLE
Alignment from txt test not passing

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#19]
This issue is 2-fold. One, the `testAlignText` is not passing. Two, Travis, is giving a false positive.

**Comment by joanise** [comment]
Fixed the test suite: the ref was created via `create_input_tei()`, while the unit test called the apparently obsolete `create_input_xml()` instead.

@roedoejet I don't know if the false positive from Travis has been fixed yet, leaving this open for you to review first.
