### ISSUE TITLE
NamedTemporaryFiles must be closed before being read on Windows

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio#23]
This issues is specific to Windows, the problem does not occur on *nix systems, because of how files are opened. On Windows, a write file handle has an exclusive lock, preventing a read file handle from being opened on the same file before the write handle is closed. As a consequence, the way we use `NamedTemporaryFile` in `readalongs/align.py` methods `create_input_xml()` and `create_input_tei()` is broken on Windows.

For cross-platform compatibility, this is the required workflow, which I know is a bit of a pain:
 - `tempfile=NamedTemporaryFile(..., delete=False)`
 - write to `tempfile`
 - close `tempfile` (which would cause the file to be deleted if we had used `delete=True`)
 - open `tempfile.name()` for reading
 - track `tempfile.name()` whereever we still need it to delete it once we're actually done with it.

Yuck, I know.

Fixing this should solve issue #20, which I believe is another symptom of the same problem.

To reproduce, on Windows only:

    cd test
    python test_force_align.py

Observed behaviour:
 - cannot open temp file that was just created
 - warning message complaining about unclosed handle
 - test suite fails

**Comment by littell** [comment]
Coincidentally, I was tracking down this one yesterday too.  We do this with other temporary files (like the dict and fsg files) but not the temporary xml we make from plain text.  (It's the os.unlink() calls at the end of the script.)

Relatedly, we should have been checking save_temps before unlinking the temporary files, we're inadvertantly unlinking the ones asks us to save, too.  (You and I noticed that but thought "Oh, maybe we only want to save them if something goes wrong."  Nope, it was a bug.)

**Comment by littell** [comment]
Rather than checking save_temps all the time to decide what kind of file to use, we should probably just create a sort of TempfileHandler class, to which we pass save_temps at construction time, and any time we need to open or cleanup a temp file ask it to do the appropriate thing.

**Comment by joanise** [comment]
I like the suggestion of a list of temps to delete at the end. The only issue is that it has to be managed in multiple places: `readalongs/cli.py` and `test/test_force_align.py`, and ultimately anywhere `create_input_xml` or `create_input_tei` are called.

Now, your `TempfileHandler` class might solve that cleanly-ish, if the two `create*()` functions have a TempfileHandler as a parameter, to which the functions will add the files to delete, if necessary. That will force the caller to create the TempfileHandler is the calling scope, and what that handler falls out of scope, the files will get deleted. I think this is what we want to both cases.

It's not as clean as I'd like, because the caller has to pay attention to create the handler at the right scope, which won't necessarily always be the scope where `create*()` are called, though in our two cases it is.

**Comment by joanise** [comment]
Fixed in PR #24 : use `PortableNamedTemporaryFile` as a drop-in replacement for `NamedTemporaryFile` with behaviour that works correctly on all platforms.

Correct usage: close the temporary file as soon as you're done writing to it. It will get deleted when the object is garbage collected, at some unspecified time before the process exits, but after all references fall out of scope.
