### ISSUE TITLE
readalongs align -f doesn't work now that the output is a directory

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio#32]
With the change of output for `readalongs align` from a bunch of files to a directory containing them, the `-f` option no longer works:

```
$ readalongs align -l fra -s -f -i in.txt in.mp3 out
INFO - Server initialized for eventlet.
Usage: readalongs align [OPTIONS] INPUTFILE WAVFILE OUTPUT_BASE

Error: Output folder 'out' already exists
```

Expected behaviour: with `-f`, the output folder is allowed to exist already, and files therein should get overwritten.

**Comment by roedoejet** [comment]
Fixed: d9f2c1a
