### ISSUE TITLE
TokenizerLibrary initializing all mappings

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#39]
The `TokenizerLibrary` class (`readalongs/tetx/tokenize_xml.py`) is currently initializing with every single available mapping. See its constructor:

```python
 def __init__(self):
        self.tokenizers = {None: DefaultTokenizer()}
        for x in MAPPINGS_AVAILABLE:
            mapping = Mapping(in_lang=x["in_lang"], out_lang=x["out_lang"])
            tokenizer_key = self.get_tokenizer_key(x["in_lang"], x["out_lang"])
            self.tokenizers[tokenizer_key] = Tokenizer(mapping)
```

We should instead just load the mappings necessary in the path from the input to `eng-arpabet`

**Comment by joanise** [comment]
Working on this as part of migrating the tokenizer to g2p.

**Comment by joanise** [comment]
Fixed with https://github.com/roedoejet/g2p/pull/82 and subsequent work.
