### ISSUE TITLE
Allow exported readalongs to be standalone (offline-safe)

### ISSUE THREAD

**Issue by eddieantonio** [ReadAlongs/Studio#57]
We want to generate readalongs that can be used entirely standalone, **without requiring a stable internet connection**.

We want to both get the latest greatest features, but also have stable component, so we have to figure out how to allow creators of readalongs the choice to use a stable version vs. choosing to have the latest version.

Why stable, and offline-friendly?

 - bad/expensive mobile internet connections
 - bad or non-existent WiFi when demoing
 - the third-party servers hosting fonts/JS suddently disappear 😱 
 - have a standalone component you can give to a community that will work for as long as possible

**Comment by roedoejet** [comment]
Closed by https://github.com/ReadAlongs/Studio/pull/78
