### ISSUE TITLE
ePub compliance

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/Studio#6]
Currently the ePubs need a bit of work to function properly on iOS, which probably is because we are not quite producing valid EPUB 2.0 or 3.0 yet (I think 3.0 is supported so we should target that)

I'll try to get this going in the next few days (making an issue here to track the work, etc)

**Comment by roedoejet** [comment]
Looks like this module might be helpful? https://github.com/aerkalov/ebooklib

**Comment by roedoejet** [comment]
ePub compatibility is currently abandoned and removed from CLI as of https://github.com/ReadAlongs/Studio/pull/90
