### ISSUE TITLE
[With Solution] Outdated Docker File Regarding Werkzeug Package

### ISSUE THREAD

**Issue by tobyatgithub** [ReadAlongs/Studio#60]
**BUG reproduce:**
If you follow the Docker instruction under the `Usage` guidance:
```
git clone ...
cd ...
docker build . --tag=readalong-studio
```

You will see an error as:
```
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/usr/local/lib/python3.7/dist-packages/werkzeug/local.py)
```

**Potential Cause:**
This is due to the `Werkzeug==0.16.0` requirement in the `Dockerfile`. And that version of Werkzeug will not work with the latest `Flask` framework.

**Potential Solution:**
One workaround is to comment out the related part in the `Dockerfile`
```
#RUN python3 -m pip uninstall -y Werkzeug
#RUN python3 -m pip install Werkzeug==0.16.0
```

**Issues:**
1. I haven't tested whether the code with the new Werkzeug version (2.0.1 currently) will work with other functionalities.
2. However, I wonder whether the `Werkzeug` package is even necessary as I don't find it in the `requirments.txt` and the pip readalongs version is working fine.

**Comment by joanise** [comment]
Just noticed this issue, sorry for not commenting sooner. I expect it's an outdated dependency, but I would have to check. Thanks for reporting it!

**Comment by joanise** [comment]
I notice you closed your PR related to this issue. Is there a problem with the PR you submitted?

**Comment by tobyatgithub** [comment]
Oh hi joanise, I initially was meant to commit that PR to my own fork but pushed it to the main branch accidentally 😂.

At the mean time, I believe removing these two lines will solve the docker issue for now. (although I think the better way will be to lock version for both flask and werkzeug, which I haven't explored yet.)

Let me know how you like this solution, and I can make a new PR towards the main branch:D

**Comment by joanise** [comment]
Hi @tobyatgithub,
No worries about the accidental push. I just reviewed the Dockerfile, and I looks to me like at some point, the default version of Werkzeug installed was the wrong one and had to be fixed. Now I suspect the line `RUN python3 -m pip install -r $APPHOME/requirements.txt` picks up the right version, so I would just delete the two lines doing explicit uninstall/install for Werkzeug if you now find that it installs a good version by default. I see that Flask now requires Werkzeug >= 2.0 so it's not surprising an explicit install of 0.16.0 would cause trouble.

I also like the documentation you added to the README, so I'll be happy to review and merge your PR if you're willing to resubmit it.
