### ISSUE TITLE
images when using URL not working

### ISSUE THREAD

**Issue by marctessier** [ReadAlongs/Studio#71]
Trying to add an image to to a RA using a  url , configured  in a  json config file..

example json file used:

```
{
    "images":
        { "0": "https://www.btb.termiumplus.gc.ca/images/termium-wet.png"}
}
```

I ran it like this:
readalongs align --config 1.json  --text-input 1.Welcome.txt 1.Welcome.mp3 1

NOTE: I did get this good  warning message when producing the RA at the end. 

_WARNING - Please make sure https://www.btb.termiumplus.gc.ca/images/termium-wet.png is accessible to clients using your read-along._

When we look at the my local http server access  logs,  we can see the  the RA tried to hit the server with a GET  and got a 404.  Technically , we should not be seeing that hit where my browser should have hit  the site "www.btb.termiumplus.gc.ca " instead.  Also notice how it tried to use the "/assets" folder as well.  The warning message was  correct in saying  "Please make sure XXXX  is accessible to clients using your read-along".

10.0.2.2 - - [19/Aug/2021 10:46:29] code 404, message File not found
10.0.2.2 - - [19/Aug/2021 10:46:29] "GET /assets/https://www.btb.termiumplus.gc.ca/images/termium-wet.png HTTP/1.1" 404 -

( Also technically this should be a ReadAlong-Web-Component bug I think)

**Comment by joanise** [comment]
Does this issue occur with DT's version too, or just the default one? I believe it's fixed in his version and PR.

**Comment by marctessier** [comment]
OK, tested using  the latest  native ReadAlong-Web-Component  ( and also DT's  version of the ReadAlong-Web-Component )   

This url images work using that .

In a nut shell , Once the 2 default URL's below are updated with the  latest ReadAlong-Web-Component, this issue will be resolved.

```
    <script type="module" src='https://unpkg.com/@roedoejet/readalong@latest/dist/read-along/read-along.esm.js'></script>
    <script nomodule src='https://unpkg.com/@roedoejet/readalong@latest/dist/read-along/read-along.js'></script>
```

**Comment by joanise** [comment]
@marctessier  I believe this issue has been fixed, since we merged the big WebComponent PR a while ago. Is that correct?

**Comment by marctessier** [comment]
I  just re-tested, confirmed all is  now  working properly.

Got this message at the bottom of logs while processing.
WARNING - Please make sure https://www.btb.termiumplus.gc.ca/images/termium-wet.png is accessible to clients using your read-along.

The WebComponent  is also property displayed the image.  

This can be closed now.
Thanks!

 
![image](https://user-images.githubusercontent.com/48233170/143471708-004631e8-2c21-4d7d-933d-af2cfb3c882c.png)

**Comment by marctessier** [comment]
closing now since  resolved.

**Comment by joanise** [comment]
Sweet, thanks for retesting!
