### ISSUE TITLE
CI/CD failed

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#83]
It looks like the release is being created but the version bump is not updating to the master branch. See https://github.com/ReadAlongs/Studio/runs/3885903392

**Comment by roedoejet** [comment]
I think it's still open actually!

**Comment by joanise** [comment]
Failed again on our release workflow today: https://github.com/ReadAlongs/Studio/actions/runs/3463722612

The problem is that the `release` and `master` branches are protected, so the action workflow cannot push to them.

**Comment by roedoejet** [comment]
I say unless @joanise figures out another solution, we should just delete that bit and merge by hand.

**Comment by joanise** [comment]
I'm almost ready to conclude the same thing @roedoejet . The GitHub documentation is providing alternatives like have a user PAT with admin-level push privileges that have the right to ignore branch protection, but then that push won't come from the token that blocks circular action activation, so I think it's going to be a pretty big can of worms.
See https://github.com/marketplace/actions/push-to-status-check-protected-branches

A simpler solution would be for the workflow to push the `_version.py` branch and create a PR to master from it. I'm looking into that.
